### ISSUE TITLE
How to make the table appear in the simulator?

### ISSUE THREAD

**Issue by iskanderuse** [icub-training/assignment_make-it-roll-iskanderuse#1]
How to make the table appear in the simulator? 
![look_down](https://user-images.githubusercontent.com/24224293/52671525-5b662c80-2f2c-11e9-9a44-93c28568b14b.gif)

**Comment by pattacini** [comment]
Hi @iskanderuse 

Please, follow [these notes][1] outlined within the instructions.

[1]: https://github.com/icub-training/assignment_make-it-roll-iskanderuse#notes
